Fall2024-Assignment3-cbpausina/Models/Entities/Movie.cs
using System.ComponentModel.DataAnnotations;

namespace Fall2024_Assignment3_cbpausina.Models.Entities
{
    public class Movie
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Url] // Ensures link is valid URL format
        public string IMDbLink { get; set; }

        public string Genre { get; set; }

        [Range(1880, 2100)]
        public int YearOfRelease { get; set; }

        public byte[]? Poster { get; set; }

        public virtual ICollection<MovieActor> MovieActors { get; set; } = new List<MovieActor>();

        public IList<string>? Reviews { get; set; }

        public IList<double>? ReviewSentiment { get; set; }
    }
}

Fall2024-Assignment3-cbpausina/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fall2024_Assignment3_cbpausina.Data;
using Fall2024_Assignment3_cbpausina.Models.Entities;
using Fall2024_Assignment3_cbpausina.Models.ViewModels;
using Fall2024_Assignment3_cbpausina.Controllers.API;

namespace Fall2024_Assignment3_cbpausina.Controllers
{
    public class ActorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly OpenAIAPIController _openAi;
        private readonly VaderSharpTool _vaderSharp;

        public ActorController(ApplicationDbContext context, OpenAIAPIController openAi, VaderSharpTool vaderSharp)
        {
            _context = context;
            _openAi = openAi;
            _vaderSharp = vaderSharp;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Actors.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .Include(m => m.MovieActors)
                    .ThenInclude(ma => ma.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (actor == null)
            {
                return NotFound();
            }

            // Get list of movies associated with actor
            var movies = actor.MovieActors.Select(ma => ma.Movie).ToList();

            // Check if tweets already exist, no need to generate if they do
            if (actor.Tweets == null || !actor.Tweets.Any())
            {
                var generatedTweets = await _openAi.TwitterApiSim(actor.Name);
                actor.Tweets = generatedTweets;

                actor.TweetSentiment = _vaderSharp.AnalyzeTweets(generatedTweets);

                // Save generated reviews to the database
                _context.Actors.Update(actor);
                await _context.SaveChangesAsync();
            }

            var vm = new ActorDetailsViewModel(actor, movies, actor.Tweets, actor.TweetSentiment);

            return View(vm);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Gender,Age,IMDbLink")] Actor actor, IFormFile? photo)
        {
            if (ModelState.IsValid)
            {
                if (photo != null && photo.Length > 0)
                {
                    using var memoryStream = new MemoryStream();
                    await photo.CopyToAsync(memoryStream); // asynchronous
                    actor.Photo = memoryStream.ToArray();
                }

                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Gender,Age,IMDbLink")] Actor actor, IFormFile? photo)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (photo != null && photo.Length > 0)
                {
                    using var memoryStream = new MemoryStream();
                    await photo.CopyToAsync(memoryStream); // asynchronous
                    actor.Photo = memoryStream.ToArray();
                }

                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.Actors.FindAsync(id);
            if (actor != null)
            {
                _context.Actors.Remove(actor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.Actors.Any(e => e.Id == id);
        }
    }
}

Fall2024-Assignment3-cbpausina/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fall2024_Assignment3_cbpausina.Data;
using Fall2024_Assignment3_cbpausina.Models.Entities;
using Fall2024_Assignment3_cbpausina.Models.ViewModels;
using Fall2024_Assignment3_cbpausina.Controllers.API;

namespace Fall2024_Assignment3_cbpausina.Controllers
{
    public class MovieController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly OpenAIAPIController _openAi;
        private readonly VaderSharpTool _vaderSharp;

        public MovieController(ApplicationDbContext context, OpenAIAPIController openAi, VaderSharpTool vaderSharp)
        {
            _context = context;
            _openAi = openAi;
            _vaderSharp = vaderSharp;
        }

        public async Task<IActionResult> GetMoviePoster(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null || movie.Poster == null)
            {
                return NotFound();
            }

            var data = movie.Poster;
            return File(data, "image/jpg");
        }

        // GET: Movie
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movie.ToListAsync());
        }

        // GET: Movie/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.MovieActors)
                    .ThenInclude(ma => ma.Actor)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (movie == null)
            {
                return NotFound();
            }

            // Get list of actors associated with movie
            var actors = movie.MovieActors.Select(ma => ma.Actor).ToList();

            // Check if reviews already exist, no need to generate if they do
            if (movie.Reviews == null || !movie.Reviews.Any())
            {
                var generatedReviews = await _openAi.GenerateTenMovieReviews(movie.Title, movie.YearOfRelease);
                movie.Reviews = generatedReviews;

                movie.ReviewSentiment = _vaderSharp.AnalyzeReviews(generatedReviews);

                // Save generated reviews to the database
                _context.Movie.Update(movie);
                await _context.SaveChangesAsync();
            }

            var vm = new MovieDetailsViewModel(movie, actors, movie.Reviews, movie.ReviewSentiment);

            return View(vm);
        }

        // GET: Movie/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,IMDbLink,Genre,YearOfRelease")] Movie movie, IFormFile? poster)
        {
            if (ModelState.IsValid)
            {
                if (poster != null && poster.Length > 0)
                {
                    using var memoryStream = new MemoryStream();
                    await poster.CopyToAsync(memoryStream); // asynchronous
                    movie.Poster = memoryStream.ToArray();
                }

                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movie/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movie/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,IMDbLink,Genre,YearOfRelease")] Movie movie, IFormFile? poster)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (poster != null && poster.Length > 0)
                {
                    using var memoryStream = new MemoryStream();
                    await poster.CopyToAsync(memoryStream); // asynchronous
                    movie.Poster = memoryStream.ToArray();
                }

                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movie/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            if (movie != null)
            {
                _context.Movie.Remove(movie);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }
    }
}

Fall2024-Assignment3-cbpausina/Views/Movie/Create.cshtml
@model Fall2024_Assignment3_cbpausina.Models.Entities.Movie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IMDbLink" class="control-label"></label>
                <input asp-for="IMDbLink" class="form-control" />
                <span asp-validation-for="IMDbLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfRelease" class="control-label"></label>
                <input asp-for="YearOfRelease" class="form-control" />
                <span asp-validation-for="YearOfRelease" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" type="file" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group my-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fall2024-Assignment3-cbpausina/Views/Movie/Delete.cshtml
@model Fall2024_Assignment3_cbpausina.Models.Entities.Movie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IMDbLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IMDbLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearOfRelease)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poster)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poster)
        </dd> *@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Fall2024-Assignment3-cbpausina/Views/Movie/Details.cshtml
@model Fall2024_Assignment3_cbpausina.Models.ViewModels.MovieDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.IMDbLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.IMDbLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.YearOfRelease)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.YearOfRelease)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Poster)
        </dt>
        <dd class = "col-sm-10">
            @if (Model.Movie.Poster != null && Model.Movie.Poster.Length > 0)
            {
                var base64 = Convert.ToBase64String(Model.Movie.Poster);
                var imgSrc = $"data:image/jpg;base64,{base64}";
                <img src="@imgSrc" width="100" height="100" />

                //<img src="@Url.Action("GetMoviePoster", "Movie", new { Model.Id })" width="100" height="100" />
            }
            else
            {
                <p>No poster available.</p>
                // If no poster, display this message instead
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Movie.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<h5 class="text-center mt-5">Actors</h5>
<table id="actors" class="table">
    <thead>
        <tr class="table-primary">
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Actors)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="Actor" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-controller="Actor" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-controller="Actor" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<h5 class="text-center mt-5">Reviews</h5>
@{
if (Model.Movie.ReviewSentiment.Count > Model.Movie.Reviews.Count){
    <h6>Overall sentiment of reviews: @Model.Movie.ReviewSentiment[Model.Movie.Reviews.Count]</h6>
}
}
<table id="reviews" class="table">
    <thead>
        <tr class="table-primary">
            <th>Review</th>
            <th>Sentiment Analysis</th>
        </tr>
    </thead>
    <tbody>
        @for (int j = 0; j < Model.Movie.Reviews.Count; j++)
        {
            <tr>
                <td>@Model.Movie.Reviews[j]</td>
                <td>@Model.Movie.ReviewSentiment[j]</td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#actors').DataTable();
        });
        $(document).ready(function () {
            $('#reviews').DataTable();
        });
    </script>
}

Fall2024-Assignment3-cbpausina/Views/Movie/Edit.cshtml
@model Fall2024_Assignment3_cbpausina.Models.Entities.Movie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IMDbLink" class="control-label"></label>
                <input asp-for="IMDbLink" class="form-control" />
                <span asp-validation-for="IMDbLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfRelease" class="control-label"></label>
                <input asp-for="YearOfRelease" class="form-control" />
                <span asp-validation-for="YearOfRelease" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" type="file" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group my-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fall2024-Assignment3-cbpausina/Views/Movie/Index.cshtml
@model IEnumerable<Fall2024_Assignment3_cbpausina.Models.Entities.Movie>

@{
    ViewData["Title"] = "Index";
}

<h1>Movie Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table id="moviesIndex" class="table table-hover">
    <thead>
        <tr class ="table-primary">
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poster)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IMDbLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearOfRelease)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @if (item.Poster != null && item.Poster.Length > 0)
                    {
                        var base64 = Convert.ToBase64String(item.Poster);
                        var imgSrc = $"data:image/jpg;base64,{base64}";
                        <img src="@imgSrc" width="100" height="100" />

                        //<img src="@Url.Action("GetMoviePoster", "Movie", new { Model.Id })" width="100" height="100" />
                    }
                    else
                    {
                        <p>No photo available.</p>
                        // If no photo, display this message instead
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IMDbLink)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearOfRelease)
                </td>
                @* <td>
            @Html.DisplayFor(modelItem => item.Poster)
            </td> *@
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@* <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IMDbLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearOfRelease)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.Poster)
            </th> 
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IMDbLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearOfRelease)
            </td>
            @* <td>
                @Html.DisplayFor(modelItem => item.Poster)
            </td> 
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>
 *@
@section Scripts {
    <script>
        $(document).ready(function() {
            $('#moviesIndex').DataTable();
        });
    </script>
}